### ISSUE TITLE
fcntl dependency not available in Windows

### ISSUE THREAD

**Issue by RainfallNZ** [tethys-ts/hdf5-tools#26]
When importing tethysts on a windows 10 machine a ModuleNotFoundError was returned with "No Module named 'fcntl'.
It is imported as part of hdf5tools\core.py line 17.
Googling fcntl shows that it is not available for Windows.
The work around is to use linux.
I've added this same issue to the tethysts repository, as that is where I discovered it.

**Comment by mullenkamp** [comment]
Thanks Tim. I've fixed it (#27). Use the new version 0.4.4.
